"""
Seed article data derived from real testuser classifications.

50 articles across 10 categories, used to build a realistic
multi-category dataset for UX and taxonomy tests.

Usage — import the fixture from conftest.py:
    def test_category_counts(seeded_articles):
        ai_articles = [a for a in seeded_articles if a.category == "Artificial Intelligence"]
        assert len(ai_articles) == 27

Or rely on seeded_user when you only need the User object:
    def test_something(seeded_user, recap_app):
        with recap_app.app_context():
            assert seeded_user.get_categories()[0][0] == "Artificial Intelligence"
"""

# Each dict maps 1-to-1 to the Article model columns (minus id / user_id, which are
# assigned at insert time).  Timestamps are deterministic fixed values so snapshots
# and ordering assertions don't break across runs.

SEED_ARTICLES = [
    # ── Artificial Intelligence (27) ──────────────────────────────────────────
    {
        "url_path": "https://blog.mdturp.ch/posts/2024-04-05-visual_guide_to_vision_transformer.html",
        "title": "Visual Guide to Vision Transformer",
        "summary": "This article provides a visual guide to understanding Vision Transformers (ViTs), a type of deep learning model used for image classification. It explains how the transformer architecture, initially developed for natural language processing, is adapted for image data. The guide covers the process from data preparation to model training, using visualizations and simple explanations.",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["Vision Transformers architecture", "Image data preparation for transformers", "Training process of Vision Transformers"]',
        "sub_categories": '["Deep Learning", "Image Classification", "Transformer Models"]',
        "created": "2026-04-01 10:00:00",
        "classified": "2026-04-01 10:01:00",
    },
    {
        "url_path": "https://thegradient.pub/financial-market-applications-of-llms/",
        "title": "Financial Market Applications of LLMs",
        "summary": "The article explores the potential applications of Large Language Models (LLMs) in financial markets, particularly in quantitative trading and fundamental analysis. It discusses the challenges and opportunities of using LLMs for predicting financial time series, the role of multimodal learning, and the creation of synthetic data for financial modeling.",
        "author_name": "Richard Dewey and Ciamac Moallemi",
        "category": "Artificial Intelligence",
        "key_topics": '["Applications of LLMs in financial markets", "Challenges of financial time series prediction", "Multimodal learning in finance"]',
        "sub_categories": '["Quantitative Trading", "Synthetic Data Generation", "Fundamental Analysis"]',
        "created": "2026-04-01 10:01:00",
        "classified": "2026-04-01 10:02:00",
    },
    {
        "url_path": "https://thegradient.pub/text-embedding-inversion/",
        "title": "Text Embedding Inversion",
        "summary": "The article discusses the concept of text embedding inversion, exploring how text can be recovered from embeddings used in AI systems. It delves into the challenges and methodologies of reversing embeddings back to their original text form, highlighting the potential security implications and future research directions.",
        "author_name": "Not specified",
        "category": "Artificial Intelligence",
        "key_topics": '["Text Embedding Inversion", "Retrieval Augmented Generation (RAG)", "Security Implications of Embeddings"]',
        "sub_categories": '["Neural Networks", "Data Security", "Machine Learning Techniques"]',
        "created": "2026-04-01 10:02:00",
        "classified": "2026-04-01 10:03:00",
    },
    {
        "url_path": "https://lilianweng.github.io/posts/2023-06-23-agent/",
        "title": "Building Agents with LLM as Core Controller",
        "summary": "The article explores the concept of building autonomous agents using large language models (LLMs) as their core controllers. It discusses the components of such systems, including planning, memory, and tool use, and highlights various techniques like task decomposition, self-reflection, and memory management.",
        "author_name": "Lilian Weng",
        "category": "Artificial Intelligence",
        "key_topics": '["LLM-powered autonomous agent systems", "Task decomposition and planning techniques", "Self-reflection and memory management in AI"]',
        "sub_categories": '["Autonomous Agents", "Machine Learning Techniques", "Cognitive Architecture"]',
        "created": "2026-04-01 10:03:00",
        "classified": "2026-04-01 10:04:00",
    },
    {
        "url_path": "https://smith.langchain.com/hub/majid/chain-of-density-prompt",
        "title": "Chain of Density Prompt",
        "summary": "From URL only",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["Density in AI models", "Prompt engineering", "LangChain applications"]',
        "sub_categories": '["AI Model Optimization", "Natural Language Processing", "AI Tools and Frameworks"]',
        "created": "2026-04-01 10:04:00",
        "classified": "2026-04-01 10:05:00",
    },
    {
        "url_path": "https://outerbounds.com/blog/retrieval-augmented-generation/",
        "title": "Retrieval Augmented Generation",
        "summary": "The article discusses the technique of Retrieval Augmented Generation (RAG) for enhancing the relevance of responses generated by large language models (LLMs). RAG involves augmenting prompts with context retrieved from a vector database, which helps in reducing hallucinations and improving the accuracy of LLM outputs.",
        "author_name": "Not specified",
        "category": "Artificial Intelligence",
        "key_topics": '["Retrieval Augmented Generation (RAG)", "Vector databases and embeddings", "Improving LLM response relevance"]',
        "sub_categories": '["Prompt engineering", "Fine-tuning large language models", "Data retrieval techniques"]',
        "created": "2026-04-01 10:05:00",
        "classified": "2026-04-01 10:06:00",
    },
    {
        "url_path": "https://outerbounds.com/blog/train-dolly-metaflow/",
        "title": "Train Your Own Large Language Model with Metaflow",
        "summary": "The article explains how to train a large language model (LLM) using Metaflow, with Databricks' Dolly as an example. It discusses the benefits of using Metaflow for orchestrating LLM training, such as versioning, flexible deployment, and scalable cloud compute.",
        "author_name": "Outerbounds",
        "category": "Artificial Intelligence",
        "key_topics": '["Training large language models with Metaflow", "Fine-tuning foundation models like Dolly", "Infrastructure and deployment considerations for LLMs"]',
        "sub_categories": '["Machine Learning Infrastructure", "Model Fine-tuning", "Cloud Computing for AI"]',
        "created": "2026-04-01 10:06:00",
        "classified": "2026-04-01 10:07:00",
    },
    {
        "url_path": "https://www.strangeloopcanon.com/p/what-can-llms-never-do",
        "title": "What Can LLMs Never Do?",
        "summary": "The article explores the limitations of Large Language Models (LLMs) in performing certain tasks, despite their successes in other complex areas. It discusses the inherent challenges LLMs face in reasoning, generalization, and maintaining context, which prevent them from solving problems like word puzzles or cellular automata.",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["Limitations of LLMs in reasoning and generalization", "Challenges in maintaining context and attention", "Failure of LLMs in solving simple iterative tasks"]',
        "sub_categories": '["Machine Learning", "Natural Language Processing", "Cognitive Limitations of AI"]',
        "created": "2026-04-01 10:07:00",
        "classified": "2026-04-01 10:08:00",
    },
    {
        "url_path": "https://docs.cohere.com/docs/the-cohere-platform",
        "title": "The Cohere Platform",
        "summary": "The article discusses the capabilities and applications of Cohere's large language models (LLMs), which are designed to enhance language processing in software systems. These models enable advanced text generation, search, and retrieval functionalities, and can be deployed through various platforms.",
        "author_name": "Cohere",
        "category": "Artificial Intelligence",
        "key_topics": '["Large Language Models (LLMs)", "Retrieval-Augmented Generation (RAG)", "Fine-Tuning and Deployment Options"]',
        "sub_categories": '["Language Processing Technologies", "Conversational Agents", "Semantic Search"]',
        "created": "2026-04-01 10:08:00",
        "classified": "2026-04-01 10:09:00",
    },
    {
        "url_path": "https://kaustavmukherjee-66179.medium.com/improve-retrieval-of-documents-from-vectordb-using-maximum-marginal-relevance-mmr-for-balancing-f6ae56fb9512",
        "title": "Improve Retrieval of Documents From VectorDB using Maximum Marginal Relevance (MMR)",
        "summary": "The article discusses the use of Maximum Marginal Relevance (MMR) to improve document retrieval from VectorDB by balancing relevance and diversity. It explains how MMR penalizes redundant information and provides a practical example using Langchain and ChromaDB.",
        "author_name": "Kaustav Mukherjee",
        "category": "Artificial Intelligence",
        "key_topics": '["Maximum Marginal Relevance (MMR)", "Document retrieval from VectorDB", "Langchain and ChromaDB implementation"]',
        "sub_categories": '["Vector Databases", "Search Algorithms", "Information Retrieval"]',
        "created": "2026-04-01 10:09:00",
        "classified": "2026-04-01 10:10:00",
    },
    {
        "url_path": "https://www.cowboy.vc/news/ai-ification-of-unsexy-tech",
        "title": "AI-ification of Unsexy Tech",
        "summary": "The article discusses Cowboy Ventures' focus on 'unsexy tech' and how AI is transforming these traditionally overlooked sectors. It highlights the potential for AI to enhance efficiency, streamline workflows, and improve margins in industries like manufacturing, logistics, and construction.",
        "author_name": "Jill",
        "category": "Artificial Intelligence",
        "key_topics": '["AI transformation in traditional industries", "Vertical and horizontal tech solutions", "Opportunities in legacy systems"]',
        "sub_categories": '["Vertical SaaS", "Legacy system modernization", "Industry-specific AI applications"]',
        "created": "2026-04-01 10:10:00",
        "classified": "2026-04-01 10:11:00",
    },
    {
        "url_path": "https://research.paulengstler.com/invisible-stitch/",
        "title": "Invisible Stitch: Building 3D Scenes With Depth Inpainting",
        "summary": "The article discusses advancements in 3D scene generation using depth inpainting techniques. It highlights the limitations of previous methods that rely on monocular depth estimation and introduces a novel depth completion network to improve geometric coherence.",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["3D scene generation", "Depth inpainting and completion", "Geometric consistency evaluation"]',
        "sub_categories": '["Computer Vision", "Generative Models", "Benchmarking Techniques"]',
        "created": "2026-04-01 10:11:00",
        "classified": "2026-04-01 10:12:00",
    },
    {
        "url_path": "https://zapier.com/blog/perplexity-ai/",
        "title": "Perplexity AI: A Swiss Army Knife for Information Discovery",
        "summary": "The article explores Perplexity AI, an AI-powered search engine that combines elements of ChatGPT and Google Search to provide well-cited answers to user queries. It discusses the tool's functionality and integration with search APIs.",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["AI-powered search engine functionality", "Integration with Zapier for business workflows", "Perplexity\'s pricing and future developments"]',
        "sub_categories": '["AI in Information Retrieval", "AI Integration with Business Tools", "AI Model Utilization"]',
        "created": "2026-04-01 10:12:00",
        "classified": "2026-04-01 10:13:00",
    },
    {
        "url_path": "https://www.linkedin.com/pulse/how-fine-tune-gpt-models-specific-niche-domains-solulab",
        "title": "How to Fine-Tune GPT Models for Specific Niche Domains",
        "summary": "The article discusses the process of fine-tuning GPT models for specific niche domains, detailing steps such as understanding task requirements, data preparation, model selection, and the fine-tuning process itself. It emphasizes the importance of iterative refinement and ethical considerations.",
        "author_name": "Not specified",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning GPT models", "Data preparation and model selection", "Ethical considerations in AI"]',
        "sub_categories": '["Transfer Learning", "Model Evaluation Techniques", "Domain-Specific AI Applications"]',
        "created": "2026-04-01 10:13:00",
        "classified": "2026-04-01 10:14:00",
    },
    {
        "url_path": "https://www.datacamp.com/tutorial/fine-tuning-large-language-models",
        "title": "Fine-Tuning Large Language Models",
        "summary": "The article provides a comprehensive guide on fine-tuning large language models, specifically using GPT-2 for sentiment analysis of tweets. It outlines the steps involved in selecting a pre-trained model, preparing the dataset, tokenizing the data, and using the Trainer class for fine-tuning.",
        "author_name": "Not specified",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning pre-trained language models", "Sentiment analysis using GPT-2", "Using Hugging Face libraries for model training"]',
        "sub_categories": '["Natural Language Processing", "Machine Learning Model Training", "Data Preprocessing and Tokenization"]',
        "created": "2026-04-01 10:14:00",
        "classified": "2026-04-01 10:15:00",
    },
    {
        "url_path": "https://www.datacamp.com/code-along/fine-tuning-your-own-llama-2-model",
        "title": "Fine-tuning Llama 3.2 and Using It Locally: A Step-by-Step Guide",
        "summary": "This article provides a comprehensive guide on how to fine-tune the Llama 3.2 model using Python and the Hugging Face platform. It covers accessing the model on Kaggle, fine-tuning it with a custom dataset, and exporting it to the Hugging Face Hub.",
        "author_name": "Maxime",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning Llama 3.2 model", "Using Hugging Face platform", "Converting models for local use"]',
        "sub_categories": '["Generative AI", "Machine Learning Models", "Model Deployment"]',
        "created": "2026-04-01 10:15:00",
        "classified": "2026-04-01 10:16:00",
    },
    {
        "url_path": "https://www.fuzzylabs.ai/blog-post/llmops-in-action-finetuned-llm-models-for-legal-text-summarization",
        "title": "LLMOps in Action: Finetuned LLM Models for Legal Text Summarization",
        "summary": "The article discusses the process of fine-tuning and deploying a Large Language Model (LLM) for summarizing legal texts using open source tools. It highlights the use of Matcha and details the steps involved in selecting, fine-tuning, and deploying an LLM using ZenML and Seldon Core.",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning Large Language Models", "Legal text summarization using LLMs", "Open source tools for LLMOps"]',
        "sub_categories": '["Machine Learning Infrastructure", "Open Source Software", "MLOps Pipelines"]',
        "created": "2026-04-01 10:16:00",
        "classified": "2026-04-01 10:17:00",
    },
    {
        "url_path": "https://huggingface.co/docs/transformers/en/training",
        "title": "Training",
        "summary": "The article provides a detailed guide on fine-tuning large pretrained language models using the Hugging Face Transformers library. It covers steps such as tokenization, loading datasets, configuring training arguments, and using the Trainer API.",
        "author_name": "Hugging Face",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning large language models", "Tokenization and dataset preparation", "Using Hugging Face Trainer API"]',
        "sub_categories": '["Model Training", "Natural Language Processing", "Machine Learning Tools"]',
        "created": "2026-04-01 10:17:00",
        "classified": "2026-04-01 10:18:00",
    },
    {
        "url_path": "https://hao-ai-lab.github.io/blogs/cllm/",
        "title": "Consistency Large Language Models (CLLMs)",
        "summary": "The article introduces Consistency Large Language Models (CLLMs), which are designed to operate as efficient parallel decoders, reducing inference latency by decoding multiple tokens simultaneously.",
        "author_name": "Not specified",
        "category": "Artificial Intelligence",
        "key_topics": '["Parallel decoding in large language models", "Jacobi decoding and its limitations", "Training methods for Consistency LLMs"]',
        "sub_categories": '["Natural Language Processing", "Machine Learning Optimization", "Model Efficiency"]',
        "created": "2026-04-01 10:18:00",
        "classified": "2026-04-01 10:19:00",
    },
    {
        "url_path": "https://www.datacamp.com/tutorial/pytorch-vs-tensorflow-vs-keras",
        "title": "PyTorch vs TensorFlow vs Keras",
        "summary": "The article explores the key differences between PyTorch, TensorFlow, and Keras, which are three of the most popular deep learning frameworks. It discusses their unique features, advantages, disadvantages, and specific use cases.",
        "author_name": None,
        "category": "Artificial Intelligence",
        "key_topics": '["Comparison of deep learning frameworks", "Features of PyTorch, TensorFlow, and Keras", "Pros and cons of each framework"]',
        "sub_categories": '["Deep Learning", "Machine Learning Tools", "Framework Evaluation"]',
        "created": "2026-04-01 10:19:00",
        "classified": "2026-04-01 10:20:00",
    },
    {
        "url_path": "https://dassum.medium.com/fine-tune-large-language-model-llm-on-a-custom-dataset-with-qlora-fb60abdeba07",
        "title": "Fine Tune Large Language Model (LLM) on a Custom Dataset with QLoRA",
        "summary": "The article provides a comprehensive guide on fine-tuning large language models (LLMs) using QLoRA, a method that enhances memory efficiency by quantizing model weights. It covers the process of selecting a pre-trained model, preparing a dataset, and implementing parameter-efficient fine-tuning techniques.",
        "author_name": "Dassum",
        "category": "Artificial Intelligence",
        "key_topics": '["Fine-tuning large language models", "Parameter-efficient fine-tuning with QLoRA", "Memory optimization in model training"]',
        "sub_categories": '["Natural Language Processing", "Model Training Techniques", "Quantization Methods"]',
        "created": "2026-04-01 10:20:00",
        "classified": "2026-04-01 10:21:00",
    },
    {
        "url_path": "https://andrewkchan.dev/posts/diffusion.html",
        "title": "Diffusion Models",
        "summary": "The article explores the theory and applications of diffusion models, particularly focusing on image generation. It contrasts diffusion models with other approaches like GANs and normalizing flows, and provides a detailed explanation of denoising diffusion models and their training processes.",
        "author_name": "Andrew K Chan",
        "category": "Artificial Intelligence",
        "key_topics": '["Diffusion Models in AI", "Generative Modeling Techniques", "Denoising Diffusion Probabilistic Models"]',
        "sub_categories": '["Image Generation", "Machine Learning Theory", "AI Applications"]',
        "created": "2026-04-01 10:21:00",
        "classified": "2026-04-01 10:22:00",
    },
    {
        "url_path": "https://www.linkedin.com/pulse/ai-trust-fall-tomasz-tunguz-eervc/",
        "title": "AI's Trust Fall",
        "summary": "The article discusses the trust issues associated with AI systems, particularly in the context of product management and user onboarding. It highlights the cognitive bias that makes human-performed work seem more trustworthy than AI, and suggests strategies for overcoming this bias.",
        "author_name": "Tomasz Tunguz",
        "category": "Artificial Intelligence",
        "key_topics": '["Trust issues in AI systems", "Cognitive bias towards human work", "Strategies for improving AI trustworthiness"]',
        "sub_categories": '["AI in product management", "Human-in-the-loop systems", "AI accuracy and reliability"]',
        "created": "2026-04-01 10:22:00",
        "classified": "2026-04-01 10:23:00",
    },
    {
        "url_path": "https://dr-arsanjani.medium.com/enhancing-the-reliability-of-llms-truth-triangulation-strategies-to-minimize-hallucinations-15f97d603b3a",
        "title": "Enhancing the Reliability of LLMs: Truth Triangulation Strategies to Minimize Hallucinations",
        "summary": "From URL only",
        "author_name": "Unknown",
        "category": "Artificial Intelligence",
        "key_topics": '["Reliability of LLMs", "Truth triangulation", "Minimizing hallucinations"]',
        "sub_categories": '["Natural Language Processing", "Machine Learning", "AI Reliability"]',
        "created": "2026-04-01 10:23:00",
        "classified": "2026-04-01 10:24:00",
    },
    {
        "url_path": "https://www.deeplearning.ai/the-batch/how-agents-can-improve-llm-performance/",
        "title": "How Agents Can Improve LLM Performance",
        "summary": "The article discusses the potential of AI agent workflows to significantly enhance the performance of large language models (LLMs). It highlights how iterative processes can lead to better results in tasks such as writing and coding, and introduces a framework for categorizing design patterns for building AI agents.",
        "author_name": "Andrew",
        "category": "Artificial Intelligence",
        "key_topics": '["AI agent workflows", "Iterative process in AI", "Design patterns for AI agents"]',
        "sub_categories": '["LLM performance improvement", "AI in writing and coding", "Multi-agent collaboration"]',
        "created": "2026-04-01 10:24:00",
        "classified": "2026-04-01 10:25:00",
    },
    {
        "url_path": "https://about.gitlab.com/blog/2024/05/30/how-gitlab-duo-helps-secure-and-thoroughly-test-ai-generated-code/",
        "title": "How GitLab Duo Helps Secure and Thoroughly Test AI-Generated Code",
        "summary": "The article discusses how GitLab Duo, a suite of AI features, helps secure and thoroughly test AI-generated code within the DevSecOps workflow. It provides a step-by-step guide on using GitLab Duo and GitLab Pages to mitigate risks associated with AI-generated code.",
        "author_name": "GitLab Product and Engineering Teams",
        "category": "Artificial Intelligence",
        "key_topics": '["AI-generated code security", "GitLab Duo and Pages integration", "Challenges in AI-driven software development"]',
        "sub_categories": '["DevSecOps", "Software Testing", "Security Vulnerabilities"]',
        "created": "2026-04-01 10:25:00",
        "classified": "2026-04-01 10:26:00",
    },
    {
        "url_path": "https://medium.com/@mutahar789/optimizing-rag-a-guide-to-choosing-the-right-vector-database-480f71a33139",
        "title": "Optimizing RAG: A Guide to Choosing the Right Vector Database",
        "summary": "From URL only: The blog post likely discusses strategies for optimizing RAG by selecting an appropriate vector database.",
        "author_name": "mutahar789",
        "category": "Artificial Intelligence",
        "key_topics": '["Vector databases", "Optimization strategies", "RAG system"]',
        "sub_categories": '["Database selection", "System optimization", "Data architecture"]',
        "created": "2026-04-01 10:26:00",
        "classified": "2026-04-01 10:27:00",
    },
    # ── Leadership (10) ───────────────────────────────────────────────────────
    {
        "url_path": "https://hybridhacker.email/p/my-25-year-engineering-career-retrospective",
        "title": "My 25-Year Engineering Career Retrospective",
        "summary": "The article is a reflective essay on a 25-year engineering career, offering insights and lessons learned. It covers topics such as time management, competition versus collaboration, the importance of journaling, and the value of networking.",
        "author_name": "Unknown",
        "category": "Leadership",
        "key_topics": '["Time management and overcoming procrastination", "Collaboration over competition in the workplace", "The importance of journaling and continuous learning"]',
        "sub_categories": '["Career Development", "Personal Growth", "Work-Life Balance"]',
        "created": "2026-04-01 11:00:00",
        "classified": "2026-04-01 11:01:00",
    },
    {
        "url_path": "https://paulgraham.com/greatwork.html",
        "title": "Great Work",
        "summary": "The article explores the intersection of techniques for achieving great work across various fields. It emphasizes the importance of choosing work that aligns with one's natural aptitudes and interests, and highlights the role of curiosity, ambition, and hard work.",
        "author_name": "Paul Graham",
        "category": "Leadership",
        "key_topics": '["Choosing work based on natural aptitude and interest", "The role of curiosity and ambition in achieving great work", "Challenges in identifying the right field or project"]',
        "sub_categories": '["Personal Development", "Career Guidance", "Motivation and Inspiration"]',
        "created": "2026-04-01 11:01:00",
        "classified": "2026-04-01 11:02:00",
    },
    {
        "url_path": "https://www.ivp.com/content/leadership-lookback-the-4ps-of-leadership-refined-by-lessons-learned-on-the-river/",
        "title": "Leadership Lookback: The 4Ps of Leadership Refined by Lessons Learned on the River",
        "summary": "The article discusses the importance of leaders bringing their full personalities to work, emphasizing vulnerability and humility to foster collaboration and trust. It draws parallels between leadership and fly-fishing.",
        "author_name": "Not specified",
        "category": "Leadership",
        "key_topics": '["Vulnerability and humility in leadership", "The importance of self-awareness", "Parallels between leadership and fly-fishing"]',
        "sub_categories": '["Personal development", "Team collaboration", "Self-awareness"]',
        "created": "2026-04-01 11:02:00",
        "classified": "2026-04-01 11:03:00",
    },
    {
        "url_path": "https://www.ivp.com/content/from-the-battlefield-to-the-boardroom-leadership-from-4-star-general-ret-richard-d-clarke/",
        "title": "From the Battlefield to the Boardroom: Leadership from 4-Star General (Ret.) Richard D. Clarke",
        "summary": "The article discusses the importance of communication in leadership, drawing on experiences from Ret. 4-Star General Richard D. Clarke's military career. It emphasizes the need for leaders to consistently communicate their vision and expectations.",
        "author_name": "Ret. 4-Star General Richard D. Clarke",
        "category": "Leadership",
        "key_topics": '["Importance of over-communication in leadership", "Establishing clear expectations and standards", "Adapting leadership strategies to new team dynamics"]',
        "sub_categories": '["Military Leadership", "Communication Strategies", "Team Management"]',
        "created": "2026-04-01 11:03:00",
        "classified": "2026-04-01 11:04:00",
    },
    {
        "url_path": "https://www.linkedin.com/posts/billhiggins1_recently-i-performed-a-management-exercise-activity-7190016084710764544-QTzs",
        "title": "Recently I performed a management exercise to improve productivity and happiness of my IBM watsonx Platform Engineering organization.",
        "summary": "The article discusses a management exercise conducted by Bill Higgins to enhance productivity and morale within the IBM watsonx Platform Engineering organization. By conducting interviews with team members, Higgins identified key issues such as communication breakdowns and skill gaps.",
        "author_name": "Bill Higgins",
        "category": "Leadership",
        "key_topics": '["Improving organizational productivity", "Enhancing communication within teams", "Developing non-technical skills in engineering leaders"]',
        "sub_categories": '["Organizational Development", "Employee Engagement", "Mentorship and Skill Development"]',
        "created": "2026-04-01 11:04:00",
        "classified": "2026-04-01 11:05:00",
    },
    {
        "url_path": "https://www.jamesshore.com/v2/blog/2024/a-useful-productivity-measure",
        "title": "A Useful Productivity Measure",
        "summary": "The article discusses the challenges of measuring productivity in software engineering, particularly from a leadership perspective. It explores the author's approach to addressing productivity measurement by focusing on accountability and qualitative indicators.",
        "author_name": "Unknown",
        "category": "Leadership",
        "key_topics": '["Challenges in measuring software engineering productivity", "Accountability and qualitative indicators in leadership", "Introduction of \'Product Bets\' and \'value-add capacity\'"]',
        "sub_categories": '["Engineering Leadership", "Productivity Metrics", "Organizational Accountability"]',
        "created": "2026-04-01 11:05:00",
        "classified": "2026-04-01 11:06:00",
    },
    {
        "url_path": "https://levelupwithethanevans.substack.com/p/create-your-10-year-plan",
        "title": "Create Your 10-Year Plan",
        "summary": "The article by Ethan Evans, a retired Amazon Vice President, emphasizes the importance of creating a 10-year plan for personal and career growth. It discusses the common tendency to overestimate short-term goals while underestimating long-term potential.",
        "author_name": "Ethan Evans",
        "category": "Leadership",
        "key_topics": '["Long-term career planning", "Leadership development", "Overseas assignments and their benefits"]',
        "sub_categories": '["Career growth strategies", "Personal development", "Executive leadership"]',
        "created": "2026-04-01 11:06:00",
        "classified": "2026-04-01 11:07:00",
    },
    {
        "url_path": "https://www.bvp.com/atlas/why-rigorous-customer-focus-will-get-your-startup-farther-than-any-best-practice-or-playbook",
        "title": "Why rigorous customer focus will get your startup farther than any best practice or playbook",
        "summary": "The article emphasizes the importance of a rigorous customer focus for startups, highlighting insights from founders of successful companies like Zola, Procore, BlackLine, Zoom, and Twilio.",
        "author_name": "Bessemer Venture Partners",
        "category": "Leadership",
        "key_topics": '["Importance of customer feedback in product development", "Adapting business strategies based on customer needs", "Case studies of successful startups focusing on customer-centric approaches"]',
        "sub_categories": '["Customer Experience", "Startup Growth Strategies", "Product Innovation"]',
        "created": "2026-04-01 11:07:00",
        "classified": "2026-04-01 11:08:00",
    },
    {
        "url_path": "https://review.firstround.com/unexpected-anti-patterns-for-engineering-leaders-lessons-from-stripe-uber-carta/",
        "title": "Unexpected Anti-Patterns for Engineering Leaders: Lessons from Stripe, Uber & Carta",
        "summary": "The article discusses common challenges faced by engineering leaders, particularly the pressure to increase engineering velocity without clear strategies. Will Larson shares insights on how conventional leadership advice can sometimes become counterproductive anti-patterns.",
        "author_name": "Will Larson",
        "category": "Leadership",
        "key_topics": '["Challenges in increasing engineering velocity", "Misalignment between engineering leaders and executives", "Context-specific leadership strategies"]',
        "sub_categories": '["Engineering Management", "Organizational Strategy", "Leadership Styles"]',
        "created": "2026-04-01 11:08:00",
        "classified": "2026-04-01 11:09:00",
    },
    {
        "url_path": "https://tomblomfield.com/post/750852175114174464/taking-risk",
        "title": "Taking Risk",
        "summary": "The article discusses the cultural differences between the UK and the US in terms of entrepreneurship and risk-taking. It highlights the underrepresentation of UK graduates in startup ventures compared to their US counterparts and argues that a cultural shift towards embracing risk is needed.",
        "author_name": "Tom Blomfield",
        "category": "Leadership",
        "key_topics": '["Cultural attitudes towards risk in the UK vs US", "The impact of entrepreneurship on economic growth", "The role of venture capital in fostering startups"]',
        "sub_categories": '["Entrepreneurship", "Economic Growth", "Venture Capital"]',
        "created": "2026-04-01 11:09:00",
        "classified": "2026-04-01 11:10:00",
    },
    # ── Software Architecture (6) ─────────────────────────────────────────────
    {
        "url_path": "https://sqlpad.io/tutorial/flask-by-example-implementing-a-redis-task-queue/",
        "title": "Flask by Example: Implementing a Redis Task Queue",
        "summary": "The article provides a comprehensive guide on integrating Flask with Redis to implement task queues. It explains the basics of Flask and its ecosystem, the role of Redis in web applications, and the advantages of using Flask with Redis for task management.",
        "author_name": "Unknown",
        "category": "Software Architecture",
        "key_topics": '["Introduction to Flask and its ecosystem", "Understanding Redis and its role in web applications", "Advantages of using Flask with Redis for task queues"]',
        "sub_categories": '["Web Development", "Task Queues", "Python Programming"]',
        "created": "2026-04-01 12:00:00",
        "classified": "2026-04-01 12:01:00",
    },
    {
        "url_path": "https://github.com/tesseract-ocr/tesseract/blob/main/README.md",
        "title": "Tesseract OCR Engine Documentation",
        "summary": "The article provides a comprehensive overview of the Tesseract OCR engine, detailing its features, history, and usage. It covers the transition from legacy to neural network-based OCR, compatibility, language support, and installation instructions.",
        "author_name": "Stefan Weil, Zdenko Podobny",
        "category": "Software Architecture",
        "key_topics": '["OCR engine features and capabilities", "Installation and usage instructions", "Developer integration and API usage"]',
        "sub_categories": '["Open Source Software", "Image Processing", "Software Development"]',
        "created": "2026-04-01 12:01:00",
        "classified": "2026-04-01 12:02:00",
    },
    {
        "url_path": "https://www.industrialempathy.com/posts/design-docs-at-google/",
        "title": "Design Docs at Google",
        "summary": "The article discusses the role and structure of design documents within Google's software engineering culture. It emphasizes the importance of design docs in outlining implementation strategies, documenting key design decisions, and facilitating organizational consensus.",
        "author_name": "Not specified",
        "category": "Software Architecture",
        "key_topics": '["Importance of design documents in software engineering", "Structure and components of a design doc", "Role of design docs in organizational knowledge sharing"]',
        "sub_categories": '["Documentation practices", "Software design process", "Engineering culture"]',
        "created": "2026-04-01 12:02:00",
        "classified": "2026-04-01 12:03:00",
    },
    {
        "url_path": "https://sre.google/sre-book/simplicity/",
        "title": "Simplicity",
        "summary": "The article discusses the importance of simplicity in software systems from the perspective of Site Reliability Engineering (SRE). It emphasizes the balance between system stability and agility, the reduction of accidental complexity, and the benefits of modularity.",
        "author_name": "Max Luebbe",
        "category": "Software Architecture",
        "key_topics": '["Balancing system stability and agility", "Reducing accidental complexity", "Importance of modularity and minimal APIs"]',
        "sub_categories": '["Site Reliability Engineering (SRE)", "Software Development Practices", "System Design Principles"]',
        "created": "2026-04-01 12:03:00",
        "classified": "2026-04-01 12:04:00",
    },
    {
        "url_path": "https://blog.bytebytego.com/p/the-scaling-journey-of-linkedin",
        "title": "The Scaling Journey of LinkedIn",
        "summary": "The article explores the evolution of LinkedIn's architecture as it scaled from a monolithic application to a service-oriented architecture (SOA). It discusses the challenges faced and the solutions implemented, such as database replication, caching strategies, and the development of Kafka.",
        "author_name": "Not specified",
        "category": "Software Architecture",
        "key_topics": '["Monolithic to Service-Oriented Architecture transition", "Database replication and caching strategies", "Development and role of Kafka at LinkedIn"]',
        "sub_categories": '["Scalability", "Data Management", "Microservices"]',
        "created": "2026-04-01 12:04:00",
        "classified": "2026-04-01 12:05:00",
    },
    {
        "url_path": "https://medium.com/@mutahar789/optimizing-rag-a-guide-to-choosing-the-right-vector-database-separate",
        "title": "Optimizing RAG: A Guide to Choosing the Right Vector Database (Architecture Focus)",
        "summary": "Discusses architectural patterns for integrating vector databases into RAG pipelines, covering trade-offs between Pinecone, Weaviate, and Chroma for production deployments.",
        "author_name": "mutahar789",
        "category": "Software Architecture",
        "key_topics": '["Vector database selection", "RAG pipeline architecture", "Production deployment trade-offs"]',
        "sub_categories": '["Database architecture", "System design", "AI infrastructure"]',
        "created": "2026-04-01 12:05:00",
        "classified": "2026-04-01 12:06:00",
    },
    # ── Cooking Techniques (2) ────────────────────────────────────────────────
    {
        "url_path": "https://barbecueathome.com/blogs/pit-masters-blog/the-meat-sweats-brisket-stall",
        "title": "The Meat Sweats: Brisket Stall",
        "summary": "The article delves into the phenomenon of the brisket stall, a common occurrence when smoking brisket where the internal temperature plateaus. It explores various theories behind why this happens, including evaporative cooling, and offers practical advice on overcoming it using methods like the Texas Crutch.",
        "author_name": "Chef Phil",
        "category": "Cooking Techniques",
        "key_topics": '["Brisket stall phenomenon", "Evaporative cooling in cooking", "Texas Crutch method"]',
        "sub_categories": '["Barbecue techniques", "Meat smoking tips", "Culinary science"]',
        "created": "2026-04-01 13:00:00",
        "classified": "2026-04-01 13:01:00",
    },
    {
        "url_path": "https://blog.thermoworks.com/chicken/thermal-tips-simple-roasted-chicken/",
        "title": "Thermal Tips: Simple Roasted Chicken",
        "summary": "The article provides a detailed guide on how to safely and effectively roast a chicken using specific temperature guidelines to ensure both safety and optimal taste. It emphasizes the importance of understanding the relationship between temperature and time in cooking chicken.",
        "author_name": "ThermoWorks",
        "category": "Cooking Techniques",
        "key_topics": '["Safe cooking temperatures for chicken", "Impact of temperature on chicken texture", "Cooking techniques for optimal flavor and safety"]',
        "sub_categories": '["Food Safety", "Culinary Science", "Roasting Techniques"]',
        "created": "2026-04-01 13:01:00",
        "classified": "2026-04-01 13:02:00",
    },
    # ── Culinary Arts (1) ─────────────────────────────────────────────────────
    {
        "url_path": "https://heygrillhey.com/texas-style-smoked-beef-brisket/",
        "title": "Texas Style Smoked Beef Brisket",
        "summary": "This article provides a comprehensive guide to preparing Texas Style Smoked Beef Brisket, detailing the process from selecting and trimming the brisket to smoking and serving it. The guide emphasizes the importance of patience and technique in achieving the perfect smoked brisket.",
        "author_name": "Hey Grill Hey",
        "category": "Culinary Arts",
        "key_topics": '["Smoking techniques for brisket", "Selecting and preparing brisket", "Tools and equipment for smoking"]',
        "sub_categories": '["BBQ and Grilling", "Meat Preparation", "Cooking Techniques"]',
        "created": "2026-04-01 13:02:00",
        "classified": "2026-04-01 13:03:00",
    },
    # ── Business Strategy (2) ─────────────────────────────────────────────────
    {
        "url_path": "https://www.bvp.com/atlas/the-six-ps-of-lean-product-with-kim-caldbeck",
        "title": "The Six Ps of Lean Product with Kim Caldbeck",
        "summary": "The article discusses Kim Caldbeck's approach to product marketing using 'The Six Ps' framework, which includes persona, problem, proposition, positioning, product, and promotion strategy. This method helps businesses validate their product-market fit before generating leads.",
        "author_name": "Kim Caldbeck",
        "category": "Business Strategy",
        "key_topics": '["The Six Ps framework for product marketing", "Importance of validating product-market fit", "Iterative approach to marketing strategy"]',
        "sub_categories": '["Product Marketing", "Market Research", "Customer Feedback"]',
        "created": "2026-04-01 14:00:00",
        "classified": "2026-04-01 14:01:00",
    },
    {
        "url_path": "https://tomblomfield.com/post/750852175114174464/taking-risk-startup",
        "title": "Startup Risk-Taking: UK vs US Cultural Attitudes",
        "summary": "Explores why UK university graduates are significantly less likely to start companies compared to US peers despite similar educational quality, and argues for cultural shifts in how risk and failure are perceived in European tech ecosystems.",
        "author_name": "Tom Blomfield",
        "category": "Business Strategy",
        "key_topics": '["Cultural attitudes towards startup risk", "Venture capital ecosystem differences", "Failure tolerance and innovation"]',
        "sub_categories": '["Entrepreneurship", "Startup Culture", "Risk Management"]',
        "created": "2026-04-01 14:01:00",
        "classified": "2026-04-01 14:02:00",
    },
    # ── Communication Strategies (1) ──────────────────────────────────────────
    {
        "url_path": "https://cq2.co/blog/the-best-way-to-have-complex-discussions",
        "title": "The Best Way to Have Complex Discussions",
        "summary": "From URL only: The blog post likely discusses methods or strategies for effectively engaging in complex discussions.",
        "author_name": "Unknown",
        "category": "Communication Strategies",
        "key_topics": '["Effective communication", "Complex discussions", "Discussion strategies"]',
        "sub_categories": '["Interpersonal Communication", "Conflict Resolution", "Negotiation Techniques"]',
        "created": "2026-04-01 15:00:00",
        "classified": "2026-04-01 15:01:00",
    },
    # ── Neuroscience (1) ──────────────────────────────────────────────────────
    {
        "url_path": "https://arstechnica.com/science/2024/04/sleeping-more-flushes-junk-out-of-the-brain/",
        "title": "Sleeping more flushes junk out of the brain",
        "summary": "The article discusses recent research on how neuronal activity during sleep facilitates the removal of metabolic waste from the brain. The study highlights the role of brain waves in activating the glymphatic system, which is responsible for flushing out debris via cerebrospinal fluid.",
        "author_name": "Nature, 2024",
        "category": "Neuroscience",
        "key_topics": '["Neuronal activity and sleep", "Glymphatic system and waste removal", "Implications for neurodegenerative diseases"]',
        "sub_categories": '["Brain health", "Sleep research", "Neurodegenerative disease research"]',
        "created": "2026-04-01 16:00:00",
        "classified": "2026-04-01 16:01:00",
    },
    # ── Sports Science (1) ────────────────────────────────────────────────────
    {
        "url_path": "https://www.trainerroad.com/blog/how-vo2-max-work-makes-you-fast-the-science-behind-it-all/",
        "title": "How VO2 Max Work Makes You Fast: The Science Behind It All",
        "summary": "The article explores the concept of VO2 max, a measure of aerobic capacity, and its significance in cycling performance. It debunks the myth that VO2 max is a fixed genetic trait, explaining how structured training can improve this metric.",
        "author_name": "TrainerRoad",
        "category": "Sports Science",
        "key_topics": '["VO2 max and its impact on cycling performance", "Physiological factors influencing VO2 max", "Training strategies to improve VO2 max"]',
        "sub_categories": '["Endurance Training", "Cycling Performance", "Aerobic Capacity"]',
        "created": "2026-04-01 17:00:00",
        "classified": "2026-04-01 17:01:00",
    },
    # ── Writing Techniques (1) ────────────────────────────────────────────────
    {
        "url_path": "https://tomtunguz.com/writing-separate-lines/",
        "title": "Writing Separate Lines",
        "summary": "The article discusses a writing technique where each sentence is placed on a separate line to improve clarity and rhythm. This method helps writers identify repetitive structures and enhances the reader's experience by varying sentence length.",
        "author_name": "Unknown",
        "category": "Writing Techniques",
        "key_topics": '["Writing clarity", "Sentence structure", "Reader engagement"]',
        "sub_categories": '["Writing advice", "Literary techniques", "Self-improvement in writing"]',
        "created": "2026-04-01 18:00:00",
        "classified": "2026-04-01 18:01:00",
    },
]

# Convenience: set of all unique categories present in the seed data
SEED_CATEGORIES = sorted({a["category"] for a in SEED_ARTICLES})

# Article counts per category — useful for assertion baselines in tests
SEED_CATEGORY_COUNTS = {
    "Artificial Intelligence": 27,
    "Leadership": 10,
    "Software Architecture": 6,
    "Cooking Techniques": 2,
    "Business Strategy": 2,
    "Culinary Arts": 1,
    "Communication Strategies": 1,
    "Neuroscience": 1,
    "Sports Science": 1,
    "Writing Techniques": 1,
}
