"""add digest_run table

Revision ID: 0dbf2a19c462
Revises: a1b2c3d4e5f6
Create Date: 2026-05-23 10:21:33.853378

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0dbf2a19c462"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "digest_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("week_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("week_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=True),
        sa.Column("clustering_strategy", sa.String(length=16), nullable=True),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("quality_verdict", sa.String(length=16), nullable=True),
        sa.Column("quality_notes", sa.Text(), nullable=True),
        sa.Column("digest_html", sa.Text(), nullable=True),
        sa.Column("digest_text", sa.Text(), nullable=True),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("digest_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_digest_run_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_digest_run_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("digest_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_digest_run_user_id"))
        batch_op.drop_index(batch_op.f("ix_digest_run_created_at"))

    op.drop_table("digest_run")
    # ### end Alembic commands ###
