"""add is_viewed and is_read to article

Revision ID: 2aaf7ced1217
Revises: d6542cc4090e
Create Date: 2026-05-09 20:59:05.949226

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2aaf7ced1217"
down_revision = "d6542cc4090e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_viewed", sa.Boolean(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_column("is_read")
        batch_op.drop_column("is_viewed")

    # ### end Alembic commands ###
