"""adding classified timestamp to article

Revision ID: 66e1c054e7e8
Revises: eadcbd4ebaaf
Create Date: 2024-04-19 17:09:42.406859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e1c054e7e8'
down_revision = 'eadcbd4ebaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classified', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('classified')

    # ### end Alembic commands ###
