"""add_digest_opened_at_cluster_count

Revision ID: 72b0938ea777
Revises: 6061b85db393
Create Date: 2026-05-25 11:50:51.507016

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "72b0938ea777"
down_revision = "6061b85db393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("article_embedding_hnsw_idx"),
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"m": "16", "ef_construction": "64"},
            postgresql_using="hnsw",
        )

    with op.batch_alter_table("digest_run", schema=None) as batch_op:
        batch_op.add_column(sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("cluster_count", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("digest_run", schema=None) as batch_op:
        batch_op.drop_column("cluster_count")
        batch_op.drop_column("opened_at")

    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("article_embedding_hnsw_idx"),
            ["embedding"],
            unique=False,
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"m": "16", "ef_construction": "64"},
            postgresql_using="hnsw",
        )

    # ### end Alembic commands ###
