"""make articles contents nullable

Revision ID: d6f2517572ad
Revises: 9a6e55094da4
Create Date: 2024-04-04 12:11:30.013656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f2517572ad'
down_revision = '9a6e55094da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('author_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.alter_column('key_topics',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sub_categories',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('sub_categories',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('key_topics',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('author_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('summary',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
