alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: recap
    match:
      path:
        prefix: /
name: recap-dev
region: sfo
services:
- http_port: 8000
  image:
    deploy_on_push:
      enabled: true
    registry_type: DOCR
    repository: recap-full
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: recap